site_name: MatBench
site_description: A benchmark and leaderboard for predicting materials properties
copyright: Materials Project (Maintained by Alex Dunn of HackingMaterials Group)

docs_dir: docs_src
site_dir: docs


theme:
  name: material
  palette:
    scheme: slate
    primary: grey
    accent: green
  logo: static/matbench_logo.png
  favicon: static/matbench_logo_favicon.png
  hide:
    - navigation
    - toc
  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences

repo_url: https://github.com/hackingmaterials/matbench

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
#  - stylesheets/wide_content.css