site_name: MatBench
site_description: A benchmark and leaderboard for predicting materials properties
copyright: HackingMaterials

docs_dir: docs_src
site_dir: docs


theme:
  name: material
  palette:
    scheme: slate
    primary: grey
    accent: green
  logo: static/matbench_logo.png
  favicon: static/matbench_logo_favicon.png
  hide:
    - natigation
    - toc

plugins:
  - search

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences

repo_url: https://github.com/hackingmaterials/matbench