name: LABEL_CHECK
on:
  pull_request:
    types: [opened, labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkLabel
      with:
        label: new_benchmark
    - name: Does 'pull_request' has ${{ steps.checkLabel.outputs.checkedLabel }} label?
      run: echo "${{ steps.checkLabel.outputs.hasLabel }}"
