name: Rebuild docs


# only rebuild docs when there is an update to main
on:
  push:
    branches: [ main ]

jobs:
  rebuild_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Lint
        run: |
        pip install --upgrade pip
        pip install wheel setuptools
        pip install -e . -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-docs.txt


        #
        mkdocs build





